### ISSUE TITLE
Mini Task, (Feinschliff Webseite)

### ISSUE THREAD

**Issue by SamyAteia** [adaasch/adaasch.github.io#1]
### Kleine Issues:
- [ ] Kontakt Button auf jeder unterseite (geht hoover?)
- [ ] Kontakt Button Landingpage hat kaputte links
- [ ] Beschriftung bei team kann nicht richtig den Bildern zugeordnet werden.

### Inhalte:
- [ ] Interessen Diskutieren um Profil zu bestimmen.
- [ ] Mehr Technologien in die Skill liste

### Todos Samy:
- [ ] Profil adden
- [ ] Relevante Projekte adden
